version: "3"
services:
  m5-forecasting-accuracy:
    build:
      context: .
      args:
        WORKDIR: /m5-forecasting-accuracy
    image: harupy:m5-forecasting-accuracy
    container_name: m5-forecasting-accuracy
    volumes:
      - .:/m5-forecasting-accuracy
    command: ["python", "src/main.py"]
