name: Docker
on:
  push:
    branches:
      - master
    paths:
      - Dockerfile

jobs:
  docker:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: harupy/m5-forecasting-accuracy
