name: Upload
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
jobs:
  upload:
    name: Upload Kernel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/upload
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          slug: test-script-${{ github.ref }}
          title: test-script-${{ github.ref }}
          code_file: ./src/main.py
          language: python
          kernel_type: script
          competition_sources: |
            m5-forecasting-accuracy
