name: Upload pytorch
on:
  push:
    branches:
      - master
    paths:
      - src/under_050.py
      - .github/workflows/upload-under-050.yml

jobs:
  upload:
    name: Upload Kernel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Convert script to notebook
        run: jupytext --to notebook src/under_050.py

      - uses: harupy/push-kaggle-kernel@master
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          slug: m5-under-0-50
          title: m5-under-0.50
          code_file: ./src/under_050.ipynb
          language: python
          kernel_type: notebook
          is_private: true
          enable_gpu: false
          enable_internet: true
          competition_sources: |
            m5-forecasting-accuracy
