name: Upload
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
jobs:
  upload:
    name: Upload Kernel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/upload
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          id: test
          title: test
          code_file: ./src/main.py
          competition_source: m5-forecasting-accuracy
